### PR TITLE
Sync develop branch with master

### PR DESCRIPTION
**Pull request by ehgmsdk20**

### CODE REVIEW

**Comment by platfowner** [comment]
From now on, we will merge PRs to the develop branch? @ehgmsdk20

**Review by liayoo — APPROVED** [review]
LGTM, thanks!

**Review by platfowner — APPROVED** [review]
LGTM with some questions.
Thanks!

**Comment by ehgmsdk20** [comment]
> From now on, we will merge PRs to the develop branch? @ehgmsdk20

Yes.
As a result of discussing with @liayoo, if I merge pr in the main branch, before the release branch is merged in the main branch, there seems to be a conflict when proceeding with npm publish and tag push in the main branch.
so it would be better to open feature pr in the develop branch and merge only the release branch in the master branch.
(cicd pr will also be updated to observe both develop branch and master branch)

**Comment by platfowner** [comment]
> > From now on, we will merge PRs to the develop branch? @ehgmsdk20
> 
> Yes. As a result of discussing with @liayoo, if I merge pr in the main branch, before the release branch is merged in the main branch, there seems to be a conflict when proceeding with npm publish and tag push in the main branch. so it would be better to open feature pr in the develop branch and merge only the release branch in the master branch. (cicd pr will also be updated to observe both develop branch and master branch)

Sounds great, thanks!

**Comment by ehgmsdk20** [comment]
Thanks for the reviews!

**Pull request merged**
