### PR TITLE
Feature/update package lock

### PR DESCRIPTION
**Pull request by pengin7384**

### CODE REVIEW

**Comment by platfowner** [comment]
We already have a bumps PR? https://github.com/ainblockchain/ain-js/pull/18

**Comment by pengin7384** [comment]
I missed it. In addition to that, this PR includes ain-js updating that I missed last time. Can I merge this PR and close PR #18?

**Comment by platfowner** [comment]
Can we merge both? It looks like there are some diff regarding elliptic package?

**Comment by pengin7384** [comment]
OK! Then can I merge #18 first? @platfowner

**Review by platfowner — APPROVED** [review]
Yes, please.

LGTM

**Comment by pengin7384** [comment]
Merged! Thanks for reviews 😄

**Pull request merged**
