### PR TITLE
Feature/protocol version

### PR DESCRIPTION
**Pull request by cshcomcom**

### CODE REVIEW

**Comment by platfowner** [comment]
Could you add updates for new state utilization APIs?
https://github.com/ainblockchain/ain-blockchain/pull/515

I think it's required for the protocol version update.

**Comment by cshcomcom** [comment]
Done! PTAL @platfowner

**Review by platfowner — APPROVED** [review]
LGTM
Thanks!

**Comment by cshcomcom** [comment]
Thanks for the review! Now merging

**Pull request merged**
