### PR TITLE
Feature/ehgmsdk20/cicd

### PR DESCRIPTION
**Pull request by ehgmsdk20**
Changes:
- execute test when pr is review_requested(when add reviewers) and pr is merged
  - if pr to master:
     run tests on `ain-blockchain/master` branch (testnet)
  - else if pr to develop:
     run tests on `ain-blockchain/develop` branch (mainnet)
- create release branch through github workflow
- publish package and push tag when release branch is merged

### CODE REVIEW

**Comment by platfowner** [comment]
@ehgmsdk20 
question) how's the version decided? (by the package version change in the pr?)

**Comment by ehgmsdk20** [comment]
> 

The version is automatically updated according to semantic version input(patch, minor, major).

**Comment by platfowner** [comment]
> > @ehgmsdk20 question) how's the version decided? (by the package version change in the pr?)
> 
> The version is automatically updated according to semantic version input(patch, minor, major).

then who gives the input? and how the value is decided?

**Comment by ehgmsdk20** [comment]
> > > @ehgmsdk20 question) how's the version decided? (by the package version change in the pr?)
> > 
> > 
> > The version is automatically updated according to semantic version input(patch, minor, major).
> 
> then who gives the input? and how the value is decided?

Discussed in online meeting

**Review by platfowner — APPROVED** [review]
LGTM
Thanks!

**Pull request merged**
