### PR TITLE
Add dryrun transaction APIs to ain-js

### PR DESCRIPTION
**Pull request by platfowner**
Change summary:
- Add dryrun transactoin APIs
- Add tests for dryrun transaction APIs
- Update test for updated db restoring logic

Related issues:
- https://github.com/ainblockchain/ain-blockchain/issues/1182

### CODE REVIEW

**Comment by shyun-comcom** [comment]
Since many methods require `isDryrun` flag, it would be beneficial to include `isDryrun` as an argument in sendTransaction or sendSignedTransaction.

Methods that may require the isDryrun flag:
* set methods in `ref.ts` (https://github.com/ainblockchain/ain-js/blob/master/src/ain-db/ref.ts)
  * set
  * incrementValue / decrementValue
  * setFunction, setOwner, setValue, setRule
  * deleteValue
* transfer (https://github.com/ainblockchain/ain-js/blob/master/src/wallet.ts#L224)

**Comment by platfowner** [comment]
> Since many methods require `isDryrun` flag, it would be beneficial to include `isDryrun` as an argument in sendTransaction or sendSignedTransaction.
> 
> Methods that may require the isDryrun flag:
> 
> * set methods in `ref.ts` (https://github.com/ainblockchain/ain-js/blob/master/src/ain-db/ref.ts)
>   
>   * set
>   * incrementValue / decrementValue
>   * setFunction, setOwner, setValue, setRule
>   * deleteValue
> * transfer (https://github.com/ainblockchain/ain-js/blob/master/src/wallet.ts#L224)

Just done by adding isDryrun param to all DB write methods.

PTAL~ @shyun-comcom

**Review by shyun-comcom — APPROVED** [review]
LGTM!

**Comment by platfowner** [comment]
Thanks for the review! Now merging.. @shyun-comcom

**Pull request merged**
